apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-blog
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: blog.local.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-blog
                port:
                  number: 3000
